CREATE TABLE PROJECT_TEAM(
    TEAM_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_NAME VARCHAR2(20)
);

CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_ID VARCHAR2(20),
    NAME VARCHAR2(20),
    AGE DECIMAL,
    --ROLL VARCHAR2(20) -- 팀장, 팀원
    --회원담당, 아이템담당, 게시판담당, 관리자담당
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_FK_TEAM_ID FOREIGN KEY (TEAM_ID)
REFERENCES PROJECT_TEAM (TEAM_ID);

INSERT INTO PROJECT_TEAM VALUES('AT','저스티스');
INSERT INTO PROJECT_TEAM VALUES('HT','엘카로');
INSERT INTO PROJECT_TEAM VALUES('CT','가오갤');
INSERT INTO PROJECT_TEAM VALUES('ST','어벤저스');

INSERT INTO MEMBER VALUES('01','AT','형준',34);
INSERT INTO MEMBER VALUES('02','AT','세인',35);
INSERT INTO MEMBER VALUES('03','AT','희태',21);
INSERT INTO MEMBER VALUES('04','AT','상훈',29);
INSERT INTO MEMBER VALUES('05','AT','태형',25);
INSERT INTO MEMBER VALUES('06','HT','혜리',26);
INSERT INTO MEMBER VALUES('07','HT','지은',26);
INSERT INTO MEMBER VALUES('08','HT','준',27);
INSERT INTO MEMBER VALUES('09','HT','재경',30);
INSERT INTO MEMBER VALUES('10','HT','단아',26);
INSERT INTO MEMBER VALUES('11','CT','최정훈',32);
INSERT INTO MEMBER VALUES('12','CT','윤호',31);
INSERT INTO MEMBER VALUES('13','CT','가은',29);
INSERT INTO MEMBER VALUES('14','CT','정훈',23);
INSERT INTO MEMBER VALUES('15','CT','승태',30);
INSERT INTO MEMBER VALUES('16','ST','승호',27);
INSERT INTO MEMBER VALUES('17','ST','소진',26);
INSERT INTO MEMBER VALUES('18','ST','이슬',29);
INSERT INTO MEMBER VALUES('19','ST','진태',26);
INSERT INTO MEMBER VALUES('20','ST','누리',30);

ALTER TABLE MEMBER ADD (ROLL VARCHAR2(20));
UPDATE MEMBER SET ROLL =
    CASE
        WHEN M.MEMBER_NAME IN ('형준','최정훈','혜리','승호') THEN '팀장'
        ELSE '팀원'
    END
;

CREATE SEQUENCE EXAM_SEQ;
CREATE SEQUENCE RECORD_SEQ;
CREATE SEQUENCE SUBJECT_SEQ;

CREATE TABLE EXAM(
    EXAM_SEQ DECIMAL PRIMARY KEY,
    MEMBER_ID VARCHAR2(20),
    SUBJECT_SEQ DECIMAL,
    MONTH VARCHAR2(20),
    SCORE VARCHAR2(20),
    RECORD_SEQ DECIMAL
);

CREATE TABLE RECORD(
    RECORD_SEQ DECIMAL PRIMARY KEY,
    AVERAGE VARCHAR2(20),
    GRADE VARCHAR2(20)
);

CREATE TABLE SUBJECT(
    SUBJECT_SEQ DECIMAL PRIMARY KEY,
    SUBJECT_NAME VARCHAR2(20)
);

ALTER TABLE EXAM ADD CONSTRAINT MEMBER_FK_MEMBER_ID FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBER(MEMBER_ID);
ALTER TABLE EXAM ADD CONSTRAINT SUBJECT_FK_SUBJECT_SEQ FOREIGN KEY (SUBJECT_SEQ)
REFERENCES SUBJECT(SUBJECT_SEQ);
ALTER TABLE EXAM ADD CONSTRAINT RECORD_FK_RECORD_SEQ FOREIGN KEY (RECORD_SEQ)
REFERENCES RECORD(RECORD_SEQ);

INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, 'Java');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, 'SQL');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, 'HTML5');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, 'R');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, 'Python');
